name: Terraform Apply Production

on:
  release:
    types:
    - published

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.12.2
  TERRAGRUNT_VERSION: 0.81.7
  TF_INPUT: false
  TF_VAR_azure_openai_endpoint: ${{ secrets.PRODUCTION_AZURE_OPENAI_ENDPOINT }}
  TF_VAR_azure_openai_key: ${{ secrets.PRODUCTION_AZURE_OPENAI_KEY }}
  TF_VAR_google_client_id: ${{ secrets.PRODUCTION_GOOGLE_CLIENT_ID }}
  TF_VAR_google_client_secret: ${{ secrets.PRODUCTION_GOOGLE_CLIENT_SECRET }}
  TF_VAR_secret_key_base: ${{ secrets.PRODUCTION_SECRET_KEY_BASE }}

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:

      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@2aee21aebfddefac5839497648a36a9f84342d8b
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@cc15ce9039f6c37c592fb9930b70466b229d2e9b # v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.PRODUCTION_AWS_ACCOUNT_ID }}:role/valentine-terraform-release
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply Terraform
        working-directory: terraform/env/production
        run: terragrunt apply --terragrunt-non-interactive -auto-approve